name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-linux-tests:
    runs-on: macos-latest
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_12_beta.app/Contents/Developer
      - uses: actions/checkout@v2
      - name: Generate Linux Tests
        run: swift test --generate-linuxmain
      - name: Check for git differences
        run: git diff --exit-code

  test-spm:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]

    runs-on: ${{matrix.os}}

    steps:
      - run: sudo xcode-select -s /Applications/Xcode_12_beta.app/Contents/Developer
        if: runner.os == 'macOS'
      - name: Install Swift
        if: runner.os == 'Linux'
        uses: sersoft-gmbh/SwiftyActions@v1
        with:
          branch-name: swift-5.3-branch
          version-tag: swift-5.3-DEVELOPMENT-SNAPSHOT-2020-08-18-a
      - uses: actions/checkout@v2
      - name: Build & Test
        run: swift test -v --parallel --enable-code-coverage
      - name: Generate Coverage Files
        if: runner.os == 'macOS'
        run: xcrun llvm-cov export -format="lcov" .build/debug/*PackageTests.xctest/Contents/MacOS/*PackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
      - name: Generate Coverage Files
        if: runner.os == 'Linux'
        run: llvm-cov export -format="lcov" .build/debug/*PackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage.lcov
          fail_ci_if_error: true
