name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift-version:
    outputs:
      max-supported-swift-version: '5.9'
    runs-on: ubuntu-latest
    steps: []

  test-spm:
    needs: swift-version
    strategy:
      matrix:
        os: [ macOS, ubuntu ]
        swift-version-offset: [ 0 ]
    uses: sersoft-gmbh/oss-common-actions/.github/workflows/swift-test-spm.yml@main
    with:
      os: ${{ matrix.os }}
      max-swift-version: ${{ needs.swift-version.outputs.max-supported-swift-version }}
      swift-version-offset: ${{ matrix.swift-version-offset }}
      fail-if-codecov-fails: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-xcode:
    needs: swift-version
    strategy:
      matrix:
        swift-version-offset: [ 0 ]
        platform:
          - macOS
          - iOS
          - iPadOS
          - tvOS
          - watchOS
    uses: sersoft-gmbh/oss-common-actions/.github/workflows/swift-test-xcode.yml@main
    with:
      xcode-scheme: semver
      max-swift-version: ${{ needs.swift-version.outputs.max-supported-swift-version }}
      swift-version-offset: ${{ matrix.swift-version-offset }}
      platform: ${{ matrix.platform }}
      platform-version: latest
      fail-if-codecov-fails: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
